### PR TITLE
Separate slideshow component for preloading

### PR DESCRIPTION
**Pull request by kelo221**

### CODE REVIEW

**Review by chrisrabe — APPROVED** [review]
Looks good. Preview site:

https://redot-landing-page-kelo.vercel.app/

**Comment by adikhoff** [comment]
This is way better than what we have now.

**Comment by adikhoff** [comment]
Also works well on mobile

**Review by adikhoff — APPROVED** [review]
Merge approved

**Comment by iRyzor** [comment]
Not a fan of how this problem was solved, but apart from that, it seems that it doesn't work as expected in Firefox, and separating the slideshow has caused the components to appear disorganized while the page loads.

We need to consider these kinds of things in the future before approving a pull request at lightning speed.

**Comment by kelo221** [comment]
>separating the slideshow has caused the components to appear disorganized while the page loads.

We are aware of this and looking into possible fixes

**Pull request merged**
