### PR TITLE
Updated the heart svg to remove clipping

### PR DESCRIPTION
**Pull request by Rhysjosmin**
decreased the blur so that theres no visible clipping
image

### CODE REVIEW

**Comment by kelo221** [comment]
SVG seems to be faulty after running svgcheck:
``` cmd
svgcheck .\heart-logo.svg
ERROR: Unable to parse the XML document: .\heart-logo.svg
heart-logo.svg: Line 24: Opening and ending tag mismatch: clipPath line 19 and defs
 ```

**Comment by opdev1004** [comment]
@Rhysjosmin  Maybe I will merge this after @kelo221 's svg check pass

**Comment by Rhysjosmin** [comment]
which version of svgcheck do i use?

**Comment by Rhysjosmin** [comment]
```
<svg width="200" height="192" viewBox="0 0 200 192" fill="none" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <filter id="blurFilter" x="-50%" y="-50%" width="200%" height="200%">
      <feGaussianBlur in="SourceGraphic" stdDeviation="10" />
    </filter>
  </defs>
  <g>
    <path d="M99.5 141C97.8171 140.998 96.1738 140.538 94.7839 139.68C74.1929 127.037 65.2769 118.369 60.359 112.949C49.8788 101.396 44.8615 89.5353 45.0029 76.691C45.168 61.9722 58.2237 50 74.1064 50C85.6556 50 93.6547 55.8842 98.3131 60.7849C98.4606 60.9386 98.643 61.0619 98.8477 61.1462C99.0525 61.2307 99.2749 61.2745 99.5 61.2745C99.725 61.2745 99.9474 61.2307 100.152 61.1462C100.357 61.0619 100.54 60.9386 100.687 60.7849C105.345 55.8794 113.344 50 124.893 50C140.776 50 153.832 61.9721 153.997 76.6933C154.139 89.54 149.115 101.401 138.641 112.951C133.723 118.37 124.807 127.039 104.216 139.682C102.826 140.54 101.182 140.999 99.5 141Z" fill="#FE3F02" opacity="0.36" filter="url(#blurFilter)"/>
    <path d="M99.5 144.5C97.6936 144.498 95.9297 144.005 94.4378 143.086C72.3355 129.54 62.7651 120.252 57.4863 114.445C46.2369 102.067 40.8513 89.3592 41.0031 75.5975C41.1803 59.8273 55.1942 47 72.2427 47C84.6395 47 93.2257 53.3045 98.226 58.5553C98.3844 58.7199 98.5801 58.852 98.7999 58.9424C99.0197 59.0329 99.2584 59.0798 99.5 59.0798C99.7416 59.0798 99.9803 59.0329 100.2 58.9424C100.42 58.852 100.616 58.7199 100.774 58.5553C105.774 53.2994 114.36 47 126.757 47C143.806 47 157.82 59.8273 157.997 75.6C158.149 89.3643 152.757 102.072 141.514 114.448C136.235 120.254 126.664 129.542 104.562 143.088C103.07 144.007 101.306 144.499 99.5 144.5Z" fill="#FE3F02"/>
  </g>
</svg>
```

this is the best i can do in terms of keeping it up to standard

ps: the same error occurs with most of the other logos in the folder
```
svgcheck assets/images/forum-logo.svg 
assets/images/forum-logo.svg:2: The element 'path' does not allow the attribute 'clip-rule', attribute to be removed.
assets/images/forum-logo.svg:2: The attribute 'fill' does not allow the value '#FE3F02', replaced with 'black'
ERROR: File does not conform to SVG requirements```

**Review by opdev1004 — APPROVED** [review]
I did document validation check and it's good to go.

**Pull request merged**
