### PR TITLE
[Feature] Add image optimisation

### PR DESCRIPTION
**Pull request by TheOtterlord**
- Use [`@nuxt/image`](https://image.nuxt.com/) to optimise images.

### CODE REVIEW

**Comment by opdev1004** [comment]
🥇
Can we
```
export default defineNuxtConfig({
  image: {
    format: ['avif', 'webp'],
    quality: 80
  }
})
```
?

**Comment by theotterlord** [comment]
@opdev1004  Added!

**Comment by theotterlord** [comment]
~~nevermind. adding this and switching to `NuxtPicture` (required. appears to have broken styling)~~

Styles are fixed!

**Comment by opdev1004** [comment]
It looks good to me.

But I will merge this to my branch and see then merge it to the develop branch since noone is picking up.

I guess it's because they cannot preview.

I am pretty sure everything will be logged.

**Comment by opdev1004** [comment]
Found authorImage is being used instead of post.authorImage. It is fixed and looking good to be merged to develop

**Pull request merged**
