### PR TITLE
Fixing twitter preview cards

### PR DESCRIPTION
**Pull request by TheOtterlord**
Attempt 1 is to crop the opengraph image to the recommended dimensions.

Fixing #63

### CODE REVIEW

**Comment by chrisrabe** [comment]
Is there still work that needs to be done in this PR or is it ready for review?

**Comment by adikhoff** [comment]
Is there a way to test this?

**Comment by opdev1004** [comment]
#110  it's fixed

**Comment by theotterlord** [comment]
~~Nice! Just to confirm @opdev1004, twitter previews work for you now? I wasn't able to get the embed, but it might be connection issues on my end atm~~

nvm. found the screenshot in the other pr :sweat_smile:

**Comment by opdev1004** [comment]
The image is cached so i don't know when it is going to be refreshed.

But you can try: [https://www.redotengine.org/?=](https://www.redotengine.org/?=)

**Pull request closed without merging**
